#!/usr/local/bin/python

import argparse
import logging
import unittest

from unit import *

def run_upr_testsuite(backend, host, port):
    upr_suite = unittest.TestSuite()
    upr_suite.addTest(ParametrizedTestCase.parametrize(UprTestCase, backend,
                                                       host, port))
    unittest.TextTestRunner(verbosity=2).run(upr_suite)

def run_mcd_testsuite(backend, host, port):
    mcd_suite = unittest.TestSuite()
    mcd_suite.addTest(ParametrizedTestCase.parametrize(McdTestCase, backend,
                                                       host, port))
    unittest.TextTestRunner(verbosity=2).run(mcd_suite)

def run_exp_testsuite():
    exp_suite = unittest.TestSuite()
    #exp_suite.addTest(UprTestCase('test_stream_request_with_deletes'))
    exp_suite.addTest(McdTestCase('test_delete'))
    unittest.TextTestRunner(verbosity=2).run(exp_suite)

def run_testsuite(suite, backend, host, port):
    if suite == 'all':
        run_upr_testsuite(backend, host, port)
        run_mcd_testsuite(backend, host, port)
    elif suite == 'upr':
        run_upr_testsuite(backend, host, port)
    elif suite == 'mcd':
        run_mcd_testsuite(backend, host, port)
    elif suite == 'exp':
        run_exp_testsuite(backend, host, port)
    else:
        print "Invalid testsuite type '%s'" % suite
        sys.exit(0)

def get_remote_server(backend):
    if backend == 'cb':
        return RemoteServer.CB
    elif backend == 'dev':
        return RemoteServer.DEV
    elif backend == 'mcd':
        return RemoteServer.MCD
    else:
        print "Invalid backend server type '%s'" % backend
        sys.exit(0)

def set_log_level(level):
    if level == None:
        logging.basicConfig(level=logging.ERROR)
    elif level == 1:
        logging.basicConfig(level=logging.WARNING)
    elif level == 2:
        logging.basicConfig(level=logging.INFO)
    else:
        logging.basicConfig(level=logging.DEBUG)

def main():
    parser = argparse.ArgumentParser(prog='pyupr',
                                     usage='%(prog)s [options]',
                                     add_help=False)

    parser.add_argument('-h', '--host', default='127.0.0.1',
                        help='the ip address of the server')
    parser.add_argument('-p', '--port', default=11211,
                        help='the port the server is running on')
    parser.add_argument('-s', '--suite', default='all',
                        help='testsuite to execute')
    parser.add_argument('-b', '--backend', default='cb',
                        help='backend server to run against')
    parser.add_argument('-v', '--verbosity', action='count',
                        help='verbosity level')

    args = parser.parse_args()
    backend = get_remote_server(args.backend)
    set_log_level(args.verbosity)
    run_testsuite(args.suite, backend, args.host, int(args.port))

if __name__ == "__main__":
    main()
